language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  
sudo: false


# coverall vvv
install:
  # currently version v1.0.0
  - composer require satooshi/php-coveralls

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev
  - mkdir -p build/logs

script:
  - phpunit --coverage-text --coverage-clover clover.xml

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
# coverall ^^^

# notifications:
#    email: false



#matrix:
#    allow_failures:
#        - php: hhvm


#script:
#    - composer dump-autoload
#    - ./build/tools/phpunit.phar --configuration ./build/travis-ci.xml
#    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
#    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi

#https://docs.travis-ci.com/user/languages/php#Dependency-Management-(a.k.a.-vendoring)
#install:
#  - ./bin/ci/install_dependencies.sh
#  - php vendor/vendors.php

#install:
#   - composer require symfony/framework-bundle:${SYMFONY_VERSION}
